// <auto-generated />
#nullable disable

namespace MitsAdvisor.Web.Migrations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using MitsAdvisor.Web.Data;

[DbContext(typeof(MitsadvisorContext))]
partial class MitsadvisorContextModelSnapshot : ModelSnapshot
{
  protected override void BuildModel(ModelBuilder modelBuilder)
  {
    modelBuilder
      .HasAnnotation("ProductVersion", "7.0.5")
      .HasAnnotation("Relational:MaxIdentifierLength", 63);

    NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

    modelBuilder.Entity("MitsAdvisor.Web.Models.Menu", b =>
    {
      b.Property<int>("Id")
        .ValueGeneratedOnAdd()
        .HasColumnType("integer");

      NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

      b.Property<string>("Name")
        .HasColumnType("text");

      b.Property<int?>("RestaurantId")
        .HasColumnType("integer");

      b.HasKey("Id");

      b.HasIndex("RestaurantId");

      b.ToTable("Menus");
    });

    modelBuilder.Entity("MitsAdvisor.Web.Models.MenuItem", b =>
    {
      b.Property<int>("Id")
        .ValueGeneratedOnAdd()
        .HasColumnType("integer");

      NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

      b.Property<string>("Description")
        .HasColumnType("text");

      b.Property<int?>("MenuId")
        .HasColumnType("integer");

      b.Property<string>("Name")
        .IsRequired()
        .HasMaxLength(100)
        .HasColumnType("character varying(100)");

      b.HasKey("Id");

      b.HasIndex("MenuId");

      b.ToTable("MenuItems");
    });

    modelBuilder.Entity("MitsAdvisor.Web.Models.Restaurant", b =>
    {
      b.Property<int>("Id")
        .ValueGeneratedOnAdd()
        .HasColumnType("integer");

      NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

      b.Property<string>("Name")
        .IsRequired()
        .HasMaxLength(100)
        .HasColumnType("character varying(100)");

      b.HasKey("Id");

      b.ToTable("Restaurants");
    });

    modelBuilder.Entity("MitsAdvisor.Web.Models.Menu", b =>
    {
      b.HasOne("MitsAdvisor.Web.Models.Restaurant", null)
        .WithMany("Menus")
        .HasForeignKey("RestaurantId");
    });

    modelBuilder.Entity("MitsAdvisor.Web.Models.MenuItem", b =>
    {
      b.HasOne("MitsAdvisor.Web.Models.Menu", null)
        .WithMany("MenuItems")
        .HasForeignKey("MenuId");
    });

    modelBuilder.Entity("MitsAdvisor.Web.Models.Menu", b =>
    {
      b.Navigation("MenuItems");
    });

    modelBuilder.Entity("MitsAdvisor.Web.Models.Restaurant", b =>
    {
      b.Navigation("Menus");
    });
  }
}
